logging:
  file:
    name: main.log
  level:
    sql: debug
    web: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/virtlibdatabase
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    open-in-view: off
